### ISSUE TITLE
[Feature Request] Create cross-compiled debian package of orocos-kdl via docker

### ISSUE THREAD

**Issue by aentinger** [107-systems/orocos-kdl-debian#1]
### ⚡ Feature Request

See [comment](https://github.com/107-systems/l3xz/pull/9#issuecomment-1152020204).

**Comment by wuehr1999** [comment]
Hi @aentinger
is this really necessary? There would already be a package in the mirror: liborocos-kdl-dev

**Comment by aentinger** [comment]
I missed that :facepalm: . However, the most current version available via package manager seems to be [v1.3.1](https://packages.debian.org/stretch/liborocos-kdl-dev) (released in 4/2016). Latest available version (and used within [l3xz](https://github.com/107-systems/l3xz) is [v1.5.1](https://github.com/orocos/orocos_kinematics_dynamics/tags)).
